// <auto-generated />
using System;
using Entities.Models.Databases.PostgresDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations.Postgres
{
    [DbContext(typeof(PostgresContext))]
    partial class PostgresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Tables.ApprovalConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer")
                        .HasColumnName("request_type");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("user_group_id");

                    b.Property<int>("WorkflowRole")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_role");

                    b.HasKey("Id")
                        .HasName("pk_approval_configs");

                    b.HasIndex("UserGroupId")
                        .HasDatabaseName("ix_approval_configs_user_group_id");

                    b.ToTable("approval_configs", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Compass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("ExitDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("exit_date");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("place");

                    b.Property<int?>("ProductEntryRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("product_entry_request_id");

                    b.Property<int?>("ProductExitRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("product_exit_request_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int?>("ProductStateId")
                        .HasColumnType("integer")
                        .HasColumnName("product_state_id");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_compasses");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_compasses_department_id");

                    b.HasIndex("InsertDate")
                        .HasDatabaseName("ix_compasses_insert_date");

                    b.HasIndex("ProductEntryRequestId")
                        .HasDatabaseName("ix_compasses_product_entry_request_id");

                    b.HasIndex("ProductExitRequestId")
                        .HasDatabaseName("ix_compasses_product_exit_request_id");

                    b.HasIndex("ProductStateId")
                        .HasDatabaseName("ix_compasses_product_state_id");

                    b.ToTable("compasses", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.GroupPagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int?>("GrantedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("page_id");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("user_group_id");

                    b.HasKey("Id")
                        .HasName("pk_group_page_permissions");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_group_page_permissions_granted_by_user_id");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_group_page_permissions_page_id");

                    b.HasIndex("UserGroupId")
                        .HasDatabaseName("ix_group_page_permissions_user_group_id");

                    b.ToTable("group_page_permissions", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("MaxStock")
                        .HasColumnType("integer")
                        .HasColumnName("max_stock");

                    b.Property<int>("MinStock")
                        .HasColumnType("integer")
                        .HasColumnName("min_stock");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventories_product_id");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_order_details");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_details_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_details_product_id");

                    b.ToTable("order_details", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("path");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.ToTable("pages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "dashboard",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(4976),
                            IsDeleted = false,
                            Path = "/dashboard",
                            SortOrder = 1,
                            Title = "Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "inventory_2",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8690),
                            IsDeleted = false,
                            Path = "/products",
                            SortOrder = 2,
                            Title = "Products"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "warehouse",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8692),
                            IsDeleted = false,
                            Path = "/inventory",
                            SortOrder = 3,
                            Title = "Inventory Stock"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "qr_code_scanner",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8693),
                            IsDeleted = false,
                            Path = "/scan",
                            SortOrder = 4,
                            Title = "Scan Barcode"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "assignment_return",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8694),
                            IsDeleted = false,
                            Path = "/exit-requests",
                            SortOrder = 5,
                            Title = "Product Exit Requests"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "shopping_cart",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8695),
                            IsDeleted = false,
                            Path = "/orders",
                            SortOrder = 6,
                            Title = "Orders"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "category",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8696),
                            IsDeleted = false,
                            Path = "/categories",
                            SortOrder = 7,
                            Title = "Categories"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "local_shipping",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8697),
                            IsDeleted = false,
                            Path = "/suppliers",
                            SortOrder = 8,
                            Title = "Suppliers"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "group",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8698),
                            IsDeleted = false,
                            Path = "/users",
                            SortOrder = 9,
                            Title = "User Management"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "explore",
                            InsertDate = new DateTime(2026, 8, 30, 10, 36, 22, 283, DateTimeKind.Utc).AddTicks(8698),
                            IsDeleted = false,
                            Path = "/compass",
                            SortOrder = 10,
                            Title = "Compass Log"
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AssetValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("asset_value");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<int>("InventoryType")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("purchase_price");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_barcode");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_products_supplier_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductEntryRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("FromSource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_source");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int?>("ProductStateId")
                        .HasColumnType("integer")
                        .HasColumnName("product_state_id");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("received_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_product_entry_requests");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_product_entry_requests_department_id");

                    b.HasIndex("InsertDate")
                        .HasDatabaseName("ix_product_entry_requests_insert_date");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_product_entry_requests_manager_id");

                    b.HasIndex("ProductStateId")
                        .HasDatabaseName("ix_product_entry_requests_product_state_id");

                    b.HasIndex("ReceivedByUserId")
                        .HasDatabaseName("ix_product_entry_requests_received_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_product_entry_requests_status");

                    b.HasIndex("SupervisorId")
                        .HasDatabaseName("ix_product_entry_requests_supervisor_id");

                    b.ToTable("product_entry_requests", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductEntryRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductEntryRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("product_entry_request_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductStateId")
                        .HasColumnType("integer")
                        .HasColumnName("product_state_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_product_entry_request_items");

                    b.HasIndex("ProductEntryRequestId")
                        .HasDatabaseName("ix_product_entry_request_items_product_entry_request_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_entry_request_items_product_id");

                    b.HasIndex("ProductStateId")
                        .HasDatabaseName("ix_product_entry_request_items_product_state_id");

                    b.ToTable("product_entry_request_items", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductExitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("requested_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_product_exit_requests");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_product_exit_requests_department_id");

                    b.HasIndex("InsertDate")
                        .HasDatabaseName("ix_product_exit_requests_insert_date");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_product_exit_requests_manager_id");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_product_exit_requests_requested_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_product_exit_requests_status");

                    b.HasIndex("SupervisorId")
                        .HasDatabaseName("ix_product_exit_requests_supervisor_id");

                    b.ToTable("product_exit_requests", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductExitRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProductExitRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("product_exit_request_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_product_exit_request_items");

                    b.HasIndex("ProductExitRequestId")
                        .HasDatabaseName("ix_product_exit_request_items_product_exit_request_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_exit_request_items_product_id");

                    b.ToTable("product_exit_request_items", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("exit_date");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Place")
                        .HasColumnType("text")
                        .HasColumnName("place");

                    b.Property<int?>("ProductExitRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("product_exit_request_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("qr_code");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_product_items");

                    b.HasIndex("ProductExitRequestId")
                        .HasDatabaseName("ix_product_items_product_exit_request_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_items_product_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_product_items_serial_number");

                    b.ToTable("product_items", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_product_states");

                    b.ToTable("product_states", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ScanTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BarcodeScanned")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode_scanned");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ScannerDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("scanner_device_id");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_scan_transactions");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_scan_transactions_product_id");

                    b.ToTable("scan_transactions", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Serlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Serexception")
                        .HasColumnType("text")
                        .HasColumnName("SEREXCEPTION");

                    b.Property<string>("Serlevel")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("SERLEVEL");

                    b.Property<string>("Sermessage")
                        .HasColumnType("text")
                        .HasColumnName("SERMESSAGE");

                    b.Property<string>("Serproperties")
                        .HasColumnType("text")
                        .HasColumnName("SERPROPERTIES");

                    b.Property<string>("Sertemplate")
                        .HasColumnType("text")
                        .HasColumnName("SERTEMPLATE");

                    b.Property<string>("Sertimestamp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("SERTIMESTAMP");

                    b.Property<DateTime?>("Serts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("SERTS")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_serlogs");

                    b.ToTable("SERLOGS", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PersonName")
                        .HasColumnType("text")
                        .HasColumnName("person_name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.Property<int?>("UserGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("user_group_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("UserGroupId")
                        .HasDatabaseName("ix_users_user_group_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_user_groups");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.UserPagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int?>("GrantedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("page_id");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_page_permissions");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_user_page_permissions_granted_by_user_id");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_user_page_permissions_page_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_page_permissions_user_id");

                    b.ToTable("user_page_permissions", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.ApprovalConfig", b =>
                {
                    b.HasOne("Entities.Models.Tables.UserGroup", "UserGroup")
                        .WithMany()
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_configs_user_groups_user_group_id");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Entities.Models.Tables.Compass", b =>
                {
                    b.HasOne("Entities.Models.Tables.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_compasses_departments_department_id");

                    b.HasOne("Entities.Models.Tables.ProductEntryRequest", "ProductEntryRequest")
                        .WithMany()
                        .HasForeignKey("ProductEntryRequestId")
                        .HasConstraintName("fk_compasses_product_entry_requests_product_entry_request_id");

                    b.HasOne("Entities.Models.Tables.ProductExitRequest", "ProductExitRequest")
                        .WithMany()
                        .HasForeignKey("ProductExitRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_compasses_product_exit_requests_product_exit_request_id");

                    b.HasOne("Entities.Models.Tables.ProductState", "ProductState")
                        .WithMany()
                        .HasForeignKey("ProductStateId")
                        .HasConstraintName("fk_compasses_product_states_product_state_id");

                    b.Navigation("Department");

                    b.Navigation("ProductEntryRequest");

                    b.Navigation("ProductExitRequest");

                    b.Navigation("ProductState");
                });

            modelBuilder.Entity("Entities.Models.Tables.GroupPagePermission", b =>
                {
                    b.HasOne("Entities.Models.Tables.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_group_page_permissions_users_granted_by_user_id");

                    b.HasOne("Entities.Models.Tables.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_page_permissions_pages_page_id");

                    b.HasOne("Entities.Models.Tables.UserGroup", "UserGroup")
                        .WithMany("GroupPagePermissions")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_page_permissions_user_groups_user_group_id");

                    b.Navigation("GrantedByUser");

                    b.Navigation("Page");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Entities.Models.Tables.Inventory", b =>
                {
                    b.HasOne("Entities.Models.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Tables.Notification", b =>
                {
                    b.HasOne("Entities.Models.Tables.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Tables.Order", b =>
                {
                    b.HasOne("Entities.Models.Tables.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Tables.OrderDetail", b =>
                {
                    b.HasOne("Entities.Models.Tables.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_details_orders_order_id");

                    b.HasOne("Entities.Models.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_details_products_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Tables.Product", b =>
                {
                    b.HasOne("Entities.Models.Tables.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.HasOne("Entities.Models.Tables.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_products_suppliers_supplier_id");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductEntryRequest", b =>
                {
                    b.HasOne("Entities.Models.Tables.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_product_entry_requests_departments_department_id");

                    b.HasOne("Entities.Models.Tables.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_entry_requests_users_manager_id");

                    b.HasOne("Entities.Models.Tables.ProductState", "ProductState")
                        .WithMany()
                        .HasForeignKey("ProductStateId")
                        .HasConstraintName("fk_product_entry_requests_product_states_product_state_id");

                    b.HasOne("Entities.Models.Tables.User", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_entry_requests_users_received_by_user_id");

                    b.HasOne("Entities.Models.Tables.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_entry_requests_users_supervisor_id");

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("ProductState");

                    b.Navigation("ReceivedByUser");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductEntryRequestItem", b =>
                {
                    b.HasOne("Entities.Models.Tables.ProductEntryRequest", "ProductEntryRequest")
                        .WithMany("Items")
                        .HasForeignKey("ProductEntryRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_entry_request_items_product_entry_requests_product_");

                    b.HasOne("Entities.Models.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_entry_request_items_products_product_id");

                    b.HasOne("Entities.Models.Tables.ProductState", "ProductState")
                        .WithMany()
                        .HasForeignKey("ProductStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_entry_request_items_product_states_product_state_id");

                    b.Navigation("Product");

                    b.Navigation("ProductEntryRequest");

                    b.Navigation("ProductState");
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductExitRequest", b =>
                {
                    b.HasOne("Entities.Models.Tables.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_product_exit_requests_departments_department_id");

                    b.HasOne("Entities.Models.Tables.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_exit_requests_users_manager_id");

                    b.HasOne("Entities.Models.Tables.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_exit_requests_users_requested_by_user_id");

                    b.HasOne("Entities.Models.Tables.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_exit_requests_users_supervisor_id");

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductExitRequestItem", b =>
                {
                    b.HasOne("Entities.Models.Tables.ProductExitRequest", "ProductExitRequest")
                        .WithMany("Items")
                        .HasForeignKey("ProductExitRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_exit_request_items_product_exit_requests_product_ex");

                    b.HasOne("Entities.Models.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_exit_request_items_products_product_id");

                    b.Navigation("Product");

                    b.Navigation("ProductExitRequest");
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductItem", b =>
                {
                    b.HasOne("Entities.Models.Tables.ProductExitRequest", "ProductExitRequest")
                        .WithMany()
                        .HasForeignKey("ProductExitRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_items_product_exit_requests_product_exit_request_id");

                    b.HasOne("Entities.Models.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_items_products_product_id");

                    b.Navigation("Product");

                    b.Navigation("ProductExitRequest");
                });

            modelBuilder.Entity("Entities.Models.Tables.ScanTransaction", b =>
                {
                    b.HasOne("Entities.Models.Tables.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_scan_transactions_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Tables.User", b =>
                {
                    b.HasOne("Entities.Models.Tables.UserGroup", "UserGroup")
                        .WithMany("Users")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_user_groups_user_group_id");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Entities.Models.Tables.UserPagePermission", b =>
                {
                    b.HasOne("Entities.Models.Tables.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_page_permissions_users_granted_by_user_id");

                    b.HasOne("Entities.Models.Tables.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_page_permissions_pages_page_id");

                    b.HasOne("Entities.Models.Tables.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_page_permissions_users_user_id");

                    b.Navigation("GrantedByUser");

                    b.Navigation("Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Tables.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductEntryRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Entities.Models.Tables.ProductExitRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Entities.Models.Tables.UserGroup", b =>
                {
                    b.Navigation("GroupPagePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
